name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - name: Print Secret
        run: |
          echo "${{ secrets.TEST_SECRET }}"

      - name: Check ENV_FILE
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          if [ -z "$ENV_FILE" ]; then
            echo "ENV_FILE is EMPTY"
            exit 1
          else
            echo "ENV_FILE Loaded"
          fi
